[package]
name = "tablec"
version = "0.1.0"
authors = ["naokata <snaokata@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
clap = "2.20.3"
